### ISSUE TITLE
Add Contribution Guidelines

### ISSUE THREAD

**Issue by Robbepop** [Robbepop/pdsl#12]
# Contribution Guidelines

This repository and project needs contribution guidelines to attract other talented open source developers to become interested and work on it.

For this we have to write down contribution guidelines, information and rules with the focus on empowering the collaboration between contributors.

This issue shall track all progress on that field.

## Tasks

- [x] Add `CONTRIBUTING.md` file to the repository root.
- [x] The repositories readme links to the contribution guidelines.
- [ ] ~~Design and create an issue template.~~
- [ ] ~~Design and create a PR template.~~
- [x] Add a project Code of Conduct.

## Rules

- Contributed code (via PR) shall be ..
    - .. covered with tests.
    - .. extensively documented in the small (micro) and big-picture (macro) level.
- Optionally for performance critical parts we need performance tests.
- For user facing abstractions we might need documentation about its guarantees - e.g. maximum gas costs of a procedure.
- All public API shall have a usage example in their documentation.

**Comment by Robbepop** [comment]
Commit https://github.com/Robbepop/pdsl/commit/3f9a5fe157e609235c3a27b077816fee3d31aa45 adds an initial version of our contribution guidelines. Closed.
